apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: mariadb-namespace
  labels:
    app: mariadb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mariadb
