apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-go-create-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/p-go-create
  persistentVolumeReclaimPolicy: Retain
