apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-go-create-pvc
  namespace: p-go-create
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
